from argparse import BooleanOptionalAction

ARGUMENTS = (('--delay',
              {'help': 'sets the speed of scrolling, defaults to 5',
               'type': int}),
             ('--button_start',
              {'help': 'the button that starts the scrolling when pressed, defaults to 2 (middle click)',
               'type': int}),
             ('--button_hold',
              {'help': 'if set, button_end is ignored and the scrolling will be active only while button_start is pressed',
               'action': BooleanOptionalAction}),
             ('--button_end',
              {'help': 'the button that ends the scrolling when pressed, defaults to 2 (middle click)',
               'type': int}),
             ('--dead_area',
              {'help': 'the size (in px) of the area below and above the starting point where scrolling is paused, defaults to 20',
               'type': int}),
             ('--icon_path',
              {'help': 'if specified, the icon on the path will be displayed while the scrolling mode is active, supported formats: svg, png, jpg, jpeg, gif, bmp, pbm, pgm, ppm, xbm, xpm, the path must be absolute, defaults resources/img/icon.svg (relative to the package)'}),
             ('--icon_size',
              {'help': 'the size of the icon in px, only svg images can be resized without loss of quality',
               'type': int}),
             ('--show_buttons',
              {'help': 'if set, button clicks will be printed to stdout',
               'action': BooleanOptionalAction}),
             ('--show_movement',
              {'help': 'if set, mouse movements will be printed to stdout',
               'action': BooleanOptionalAction}))
